@extends('site.layout')
@section('content')
    <section class="pt-20 pb-24 md:pb-32 overflow-hidden">
        <div class="container px-4 mx-auto">
            <div class="lg:items-center -m-8 lg:-m-12">
                <div class="w-full p-8 lg:p-12">
                    <h2 class="mb-6 block-title font-black font-heading tracking-tighter-xl">
                        As
                        <span style="color: {{ env('PRIMARY_COLOR') }}">publicações</span>
                    </h2>
                    <div class="block-description text-[#737276]">
                        A produção científica do III é grande e diversificada e nos últimos 5 anos mais de 700 artigos científicos foram publicados. Naturalmente, não é possível colocar toda essa informação nas páginas do III, mas as referências estão à disposição dos interessados. Mostramos aqui exemplos que ilustram a qualidade dos trabalhos, as parcerias entre membros do III e, também, as muitas parcerias externas.
                        <br><br>
                        Parte significativa da produção nestes últimos anos girou em torno do grande assunto do momento: a COVID-19. Abaixo uma lista ilustrativa (2022-2024).
                        <br><br>
                        <ul class="list-disc list-inside space-y-2">
                            <li>ANDRADE SA; BATALHA-CARVALHO JV; CURI R; WEN F H; COVAS DT; CHUDZINSKI-TAVASSI AM; MORO, ANA M. Equine anti-SARS-CoV-2 serum (ECIG) binds to mutated RBDs and N proteins of variants of concern and inhibits the binding of RBDs to ACE-2 receptor. Frontiers in Immunology, v. 13, p. 871874, 2022.</li>
                            <li>BOAVENTURA V S; CERQUEIRA-SILVA T; BARRAL-NETTO M. The benefit of vaccination after previous SARS-CoV-2 infection in the omicron era. LANCET INFECTIOUS DISEASES, v. 23, p. 1, 2023.</li>
                            <li>CASTELLI ECC, MATEUS V, NASLAVSKY MS, SCLIAR MO, SILVA NSB, PEREIRA RN, CIRIACO VAO, CASTRO CFB, MENDES-JUNIOR CT, SILVEIRA S, DE OLIVEIRA IM, ANTONIO EC, VIEIRA GF, MEYER D, NUNES K, MATOS LRB, SILVA MVR, WANG JYT, ESPOSITO J, CÓRIA VR, MAGAWA JY, SANTOS K S, CUNHA-NETO E, KALIL J , et al. ; MUC22, HLA-A, and HLA-DOB variants and COVID-19 in resilient super-agers from Brazil. Frontiers in Immunology, v. 13, p.</li>
                            <li>CASTRO JT, AZEVEDO P, FUMAGALLI MJ, HOJO-SOUZA NS, SALAZAR N, ALMEIDA GG, OLIVEIRA LI, FAUSTINO L, ANTONELLI LR, MARÇAL TG, AUGUSTO M, VALIATE B, FIORINI A, RATTIS B, RAMOS SG, PICCIN M, NONATO OC, BENEVIDES L, MAGALHÃES R, CASSARO B, BURLE G, DORO D, KALIL J, DURIGON E, et al. ; Promotion of neutralizing antibody-independent immunity to wild-type and SARS-CoV-2 variants of concern using an RBD-Nucleocapsid fusion protein. Nature Communications, v. 13, p. 4831, 2022.</li>
                            <li>CERQUEIRA-SILVA T ; ANDREWS JR; BOAVENTURA V ; RANZANI OT; OLIVEIRA VA; PAIXÃO, ES; JÚNIOR, JB; MACHADO, TM ; HITCHINGS MDT; DORION M; LIND ML; PENNA G; CUMMINGS DAT; DEAN NE; WERNECK GL; PEARCE N; BARRETO ML; KO AI; CRODA J; BARRAL-NETTO M. Effectiveness of CoronaVac, ChAdOx1 nCoV-19, BNT162b2, and Ad26.COV2.S among individuals with previous SARS-CoV-2 infection in Brazil: a test-negative, case-control study. LANCET INFECTIOUS DISEASES, v. 22, p. 1, 2022.</li>
                            <li>CERQUEIRA-SILVA T; DE ARAUJO OLIVEIRA V; PAIXÃO ES; JÚNIOR JB ; PENNA GO; WERNECK GL; PEARCE N; BARRETO ML; BOAVENTURA VS; BARRAL-NETTO M. Duration of protection of CoronaVac plus heterologous BNT162b2 booster in the Omicron period in Brazil. Nature Communications, v. 13, p. 4154, 2022.</li>
                            <li>CERQUEIRA-SILVA T; KATIKIREDDI SV; DE ARAUJO OLIVEIRA V; FLORES-ORTIZ R; JÚNIOR JB; PAIXÃO ES; ROBERTSON C; PENNA GO; WERNECK GL; BARRETO ML; PEARCE N; SHEIKH A; BARRAL-NETTO M; BOAVENTURA VS. Vaccine effectiveness of heterologous CoronaVac plus BNT162b2 in Brazil. NATURE MEDICINE, v. 28, p. 1, 2022.</li>
                            <li>DE CASTRO MV; SILVA MV R; NASLAVSKY MS; SCLIAR MO; NUNES K; PASSOS-BUENO MR; CASTELLI EC; MAGAWA JY; ADAMI FL; MORETTI AIS; DE OLIVEIRA VL ; BOSCARDIN SB; CUNHA-NETO E; KALIL J; JOUANGUY E; BASTARD P; CASANOVA J-L; QUIÑONES-VEGA M; SOSA-ACOSTA P; GUEDES JS; DE ALMEIDA NP; NOGUEIRA FCS; DOMONT GB; SANTOS KS; ZATZ M. The oldest unvaccinated Covid-19 survivors in South America. Immunity & Ageing, v. 19, p. 57, 2022.</li>
                            <li>DORNELES GP; TEIXEIRA PC; PERES A; RODRIGUES JÚNIOR LC; DA FONSECA, SG; MONTEIRO MC; ELLER S; OLIVEIRA TF; WENDLAND EM; ROMÃO PRT.  Endotoxin tolerance and low activation of TLR-4/NF-κB axis in monocytes of COVID-19 patients. JOURNAL OF MOLECULAR MEDICINE-JMM, v. x, p. 1, 2023</li>
                            <li>FERNANDES ER; DE SOUZA APOSTOLICO J; JACINTHO LC; CARNEVALE MARIN ML; VIEIRA DA SILVA JÚNIOR RC ; RODRIGUES H; SANTOS KS; COELHO V; BOSCARDIN SB; KALIL J; CUNHA-NETO E; ROSA, DS. Time-dependent contraction of the SARS-CoV-2-specific T-cell responses in convalescent individuals. Journal of Allergy and Clinical Immunology: Global, v. 1, p. 112-121, 2022.</li>
                            <li>GRACA L; FARIA AC; RIBEIRO RM. Illuminating a blind spot in SARS-CoV-2 immunity. NATURE IMMUNOLOGY, v. 24, p. 889-890, 2023.</li>
                            <li>MEDEIROS GX; SASAHARA GL; MAGAWA JY; NUNES JPS; BRUNO, FR; KURAMOTO, AC; ALMEIDA RR; FERREIRA MA; SCAGION GP; CANDIDO ÉD; LEAL FB; OLIVEIRA DBL; DURIGON EL; SILVA RCV; ROSA DS; BOSCARDIN SB; COELHO V; KALIL J; SANTOS KS; CUNHA-NETO E. Reduced T Cell and Antibody Responses to Inactivated Coronavirus Vaccine Among Individuals Above 55 Years Old. Frontiers in Immunology, v. 13, p. 812126, 2022.</li>
                            <li>OLIVEIRA JR; RUIZ CMR; MACHADO RRG; MAGAWA JY; DAHER IP; URBANSKI AH; SCHMITZ GJH; ARCURI HA; FERREIRA MA; SASAHARA GL; DE MEDEIROS GX; JÚNIOR RCVS; DURIGON EL; BOSCARDIN SB; ROSA DS; SCHECHTMAN D; NAKAYA HI; CUNHA-NETO E; GADERMAIER G; KALIL J; COELHO V; SANTOS KS. Immunodominant antibody responses directed to SARS-CoV-2 hotspot mutation sites and risk of immune escape. Frontiers in Immunology, v. 13, p. 1, 2023.</li>
                            <li>SERVIAN CDP, SPADAFORA-FERREIRA M, DOS ANJOS DCC, GUILARDE AO, GOMES-JUNIOR AR, BORGES MASB, MASSON LC, SILVA JMM, DE LIMA MHA, MORAES BGN, SOUZA SM, XAVIER LE, DE OLIVEIRA DCA, BATALHA-CARVALHO JV, MORO AM, BOCCA AL, PFRIMER IAH, COSTA NL, FERES VCR, FIACCADORI FS, SOUZA M, GARDINASSI LG, DURIGON EL, ROMÃO PRT, JORGE SAC, COELHO V, BOTOSSO VF, FONSECA SG.  Distinct anti-NP, anti-RBD and anti-Spike antibody profiles discriminate death from survival in COVID-19. Front Immunol. 14:1206979,2023.</li>
                            <li>MCDONNELL J, COUSINS K, YOUNGER MEM, LANE A, ABOLHASSANI H, ABRAHAM RS, AL-TAMEMI S, ALDAVE-BECERRA JC, AL-FARIS EH, ALFARO-MURILLO A, ALKHATER SA, ALSAATI N, DOSS AMA, ANDERSON M, ANGAROLA E, ARIUE B, ARNOLD DE, ASSA'AD AH, AYTEKIN C, BANK M, BERGERSON JRE, BLEESING J, BOESING J, BOUSO C, BRODSZKI N, CABANILLAS D, CADY C, CALLAHAN MA, CAORSI R, CARBONE J, CARRABBA M, CASTAGNOLI R, CATANZARO JR, CHAN S, CHANDRA S, CHAPDELAINE H, CHAVOSHZADEH Z, CHONG HJ, CONNORS L, CONSONNI F, CORREA-JIMENEZ O, CUNNINGHAM-RUNDLES C, D'ASTOUS-GAUTHIER K, DELMONTE OM, DEMIRDAG YY, DESHPANDE DR, DIAZ-CABRERA NM, DIMITRIADES VR, EL-OWAIDY R, ELGHAZALI G, AL-HAMMADI S, FABIO G, FAURE AS, FENG J, FERNANDEZ JM, FILL L, FRANCO GR, FRENCK RW, FULEIHAN RL, GIARDINO G, GALANT-SWAFFORD J, GAMBINERI E, GARABEDIAN EK, GEERLINKS AV, GOUDOURIS E, GRECCO O, PAN-HAMMARSTRÖM Q, KHANI HHK, HAMMARSTRÖM L, HARTOG NL, HEIMALL J, HERNANDEZ-MOLINA G, HORNER CC, HOSTOFFER RW, HRISTOVA N, HSIAO KC, IVANKOVICH-ESCOTO G, JABER F, JALIL M, JAMEE M, JEAN T, JEONG S, JHAVERI D, JORDAN MB, JOSHI AY, KALKAT A, KANAREK HJ, KELLNER ES, KHOJAH A, KHOURY R, KOKRON CM, KUMAR A, LECERF K, LEHMAN HK, LEIDING JW, LESMANA H, LIM XR, LOPES. COVID-19 Vaccination in Patients with Inborn Errors of Immunity Reduces Hospitalization and Critical Care Needs Related to COVID-19: a USIDNET Report. J Clin Immunol. 44(4):86, 2024.</li>
                            <li>ADAMI FL, DE CASTRO MV, ALMEIDA BDS, DAHER IP, YAMAMOTO MM, SOUZA SANTOS K, ZATZ M, NASLAVSKY MS, ROSA DS, CUNHA-NETO E, DE OLIVEIRA VL, KALIL J, BOSCARDIN SB. Anti-RBD IgG antibodies from endemic coronaviruses do not protect against the acquisition of SARS-CoV-2 infection among exposed uninfected individuals. Front Immunol. 15:1396603. 2024.</li>
                            <li>CERQUEIRA-SILVA T, BOAVENTURA VS, PEARCE N, BARRAL-NETTO M. Indirect effectiveness of COVID-19 vaccines in the pre-omicron and omicron periods: A nation-wide test-negative case-control study in Brazil. Int J Infect Dis. 148:107241, 2024.</li>
                        </ul>
                        {{--
                        <br>
                        A seguir alguns exemplos de outros assuntos de interesse da população.
                        <br><br>
                        <ul class="list-disc list-inside space-y-2">
                            <li>ANTONELLI ACB; ALMEIDA VP; DE CASTRO FOF; SILVA JM; PFRIMER IAH; CUNHA-NETO E; MARANHÃO AQ; BRÍGIDO MM; RESENDE RO; BOCCA AL; FONSECA SG. In silico construction of a multiepitope Zika virus vaccine using immunoinformatics tools. Sci.Rep. 2022,Jan7;12(1);53.</li>
                            <li>COIRADA FC; FERNANDES ER; MELLO LR; SCHUCH V; SOARES CAMPOS G; BRACONI CT; BOSCARDIN SB; SANTORO ROSA D . Heterologous DNA Prime- Subunit Protein Boost with Chikungunya Virus E2 Induces Neutralizing Antibodies and Cellular-Mediated Immunity. INTERNATIONAL JOURNAL OF MOLECULAR SCIENCES, v. 24, p. 10517, 2023.</li>
                            <li>DANELLA FIGO D; MACEDO PRC; GADERMAIER G; REMUZGO C; CASTRO FFM; KALIL J; GALVÃO CES; SANTOS KS. IgE and IgG4 Epitopes of Dermatophagoides and Blomia Allergens before and after Sublingual Immunotherapy. INTERNATIONAL JOURNAL OF MOLECULAR SCIENCES, v. 24, p. 4173-4191, 2023.</li>
                            <li>LUNARDELLI VAS; APOSTOLICO JS; SOUZA HFS; COIRADA FC; MARTINHO JA; ASTRAY RM; BOSCARDIN SB; ROSA DS. ZIKV-envelope proteins induce specific humoral and cellular immunity in distinct mice strains. Scientific Reports, v. 12, p. 1, 2022</li>
                            <li>PAIXÃO AR; TIBÚRCIO R; CARVALHO E; SILVA T; VERA, PST; TAVARES NM; DE MENEZES JPB; BRODSKYN CI. In Vitro Differentiation of Human Dendritic Cells and their Markers in Leishmania Infection. Jove-Journal of Visualized Experiments, v. 6, p. 35467651, 2022</li>
                            <li>POMÉS A; ARRUDA LK. Cockroach allergy: Understanding complex immune responses to develop novel therapies. MOLECULAR IMMUNOLOGY, v. 156, p. 157-169, 2023.</li>
                            <li>VALLE SOR; ALONSO MLO; DORTAS JUNIOR SD; GOUDOURIS ES; DE CARVALHO ALRB; CAPELO AV; MANSOUR E; BERNARDES AF; LEITE LFB; GIAVINA-BIANCHI P; AUN MV; FERRIANI MPL; ARRUDA LK; GRUMACH AS. Acquired Angioedema due to C1-Inhibitor Deficiency: A Challenging Condition. INTERNATIONAL ARCHIVES OF ALLERGY AND IMMUNOLOGY, v. 183, p. 572-577, 2022.</li>
                            <li>NUNES IV; ANDRADE CM; GUERRA PV; KHOURI MI; GALANTINI MPL; DA SILVA RAA; FAQUIM-MAURO EL; FARIAS LP; REBOUÇAS JS; FARIA AMC; BRODSKYN CI. A new experimental model to study shrimp allergy. IMMUNOLOGY LETTERS, v. 261, p. 56, 2023.</li>
                            <li>NUNEZ FA; CASTRO ACH; DAHER IP; CUNHA-NETO E; KALIL J; BOSCARDIN SB; LANFREDI AJC; OLIVEIRA VL; ALVES WA. ZnO-Based Electrochemical Immunosensor to Assess Vaccine-Induced Antibody-Mediated Immunity against Wild-Type and Gamma SARS-CoV-2 Strains. BIOSENSORS, v. 13, p. 371, 2023.</li>
                        </ul>
                        --}}
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection
